{
  "comments": [
    {
      "key": {
        "uuid": "b731cbd7_2577e2e8",
        "filename": "src/main/java/com/googlesource/gerrit/plugins/rabbitmq/session/type/AMQPSession.java",
        "patchSetId": 1
      },
      "lineNbr": 124,
      "author": {
        "id": 1011123
      },
      "writtenOn": "2018-08-30T05:27:50Z",
      "side": 1,
      "message": "Why would opening a connection result in this?  I would expect this kind of exception to occur when closing.",
      "range": {
        "startLine": 124,
        "startChar": 29,
        "endLine": 124,
        "endChar": 51
      },
      "revId": "6fba355ec5e76d8a3dc4baf17a184b001893fbe6",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": true
    }
  ]
}